DATA_PATH = 'data'
BRACE_CLASS = 'brace'
LINES_CLASSES = ['end_line', 'bar_line']
STAFF_CLASS = 'staff'

IMAGE_HEIGHT = 1320
IMAGE_WIDTH = 1868

BAR_EXTENSION = 5
BAR_LINE_FIND_RATIO = 0.6
END_LINE_FIND_RATIO = 0.45
